In [2]:
# Cell 1: Nạp dữ liệu và khởi tạo môi trường
import pandas as pd
import re
import sys
import os


# Nạp dữ liệu sạch sơ bộ từ bước 1
DATA_PATH = '../Dataset/processed/cti_dataset_cleaned.csv'

try:
    df = pd.read_csv(DATA_PATH).fillna('')
    print(f"[*] Nạp dữ liệu thành công từ: {DATA_PATH}")
    print(f"[*] Kích thước dữ liệu: {df.shape[0]} dòng, {df.shape[1]} cột.")
    
    # Kiểm tra nhanh 5 dòng đầu
    display(df.head())
    
    # Kiểm tra xem có giá trị Null nào bị sót không
    null_counts = df.isnull().sum()
    if null_counts.sum() > 0:
        print("\n Cảnh báo: Vẫn còn dữ liệu rỗng (NaN)!")
        print(null_counts[null_counts > 0])
    else:
        print("\n Dữ liệu sạch, không có giá trị rỗng.")
        
except FileNotFoundError:
    print(f"[!] Không tìm thấy file tại {DATA_PATH}. Vui lòng kiểm tra lại đường dẫn!")

[*] Nạp dữ liệu thành công từ: ../Dataset/processed/cti_dataset_cleaned.csv
[*] Kích thước dữ liệu: 13161 dòng, 17 cột.

,ID,Title,Category,Attack Type,Scenario Description,Tools Used,Attack Steps,Target Type,Vulnerability,label,Impact,Detection Method,Solution,Tags,Source,text,text_clean
0,1,Authentication Bypass via SQL Injection,Mobile Security,SQL Injection (SQLi),A login form fails to validate or sanitize inp...,"Browser, Burp Suite, SQLMap",1. Reconnaissance: Find a login form on the we...,"Web Login Portals (e.g., banking, admin dashbo...",Unsanitized input fields in SQL queries,T1078,"Full account takeover, data theft, privilege e...","Web server logs, anomaly detection (e.g., logi...","Use prepared statements, Sanitize inputs, Limi...","SQLi, Authentication Bypass, Web Security, OWA...","OWASP, MITRE ATT&CK, DVWA",Authentication Bypass via SQL Injection. A log...,Authentication Bypass via SQL Injection. A log...
1,2,Union-Based SQL Injection,AI Agents & LLM Exploits,SQL Injection,This attack occurs when a hacker uses the SQL ...,"SQLMap, Burp Suite, Havij, Browser Developer T...",1. Identify User Input Points: Attacker finds ...,"Web Applications, Login Pages, Search Forms",Improperly filtered input fields that allow SQ...,T1190,"Data leakage, Credential theft, Account takeov...",Web Application Firewalls (WAF)Log AnalysisInp...,Use parameterized queries (Prepared Statements...,#SQLInjection #WebSecurity #UnionAttack #OWASP...,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger Web...",Union-Based SQL Injection. This attack occurs ...,Union-Based SQL Injection. This attack occurs ...
2,3,Error-Based SQL Injection,AI Agents & LLM Exploits,SQL Injection,This attack occurs when an attacker intentiona...,"SQLMap, Burp Suite, Manual Browser Testing, Havij",1. Identify Input Points:Attacker finds a fiel...,"Web Applications, Login Forms, URL Parameters,...",Error message exposure due to lack of input va...,T1190,"Information disclosure, Database structure exp...",Review and monitor error logsEnable generic er...,Turn off detailed error messages in production...,#SQLInjection #ErrorLeakage #WebAppSecurity #O...,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger Web...",Error-Based SQL Injection. This attack occurs ...,Error-Based SQL Injection. This attack occurs ...
3,4,Blind SQL Injection,AI Agents & LLM Exploits,SQL Injection,"In Blind SQL Injection, the attacker doesn’t s...","SQLMap, Burp Suite, sqlninja, Manual Browser T...",1. Find a User Input Point:Attacker finds a pl...,"Web Applications, Login Pages, Search Fields, ...","No error messages, but user input is still pas...",T1190,Slow and stealthy data theftFull database comp...,Monitor for slow and repetitive requestsAnalyz...,Use parameterized queries (prepared statements...,#BlindSQLi #TimeBasedSQLi #WebAppSecurity #OWA...,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger, SQ...","Blind SQL Injection. In Blind SQL Injection, t...","Blind SQL Injection. In Blind SQL Injection, t..."
4,5,Second-Order SQL Injection,AI Agents & LLM Exploits,SQL Injection,"In a Second-Order SQL Injection, the attacker ...","Burp Suite, SQLMap, Postman, Browser Dev Tools...",1. Identify Stored Input Fields:The attacker l...,"Web Applications, User Registration Forms, Pro...",Trusting previously stored unvalidated data in...,T1505,Delayed data theftUnexpected system behaviorSe...,Log monitoring for delayed query failuresTrack...,Sanitize and validate inputs both at entry and...,#SecondOrderSQLi #DelayedInjection #StoredInje...,"OWASP, MITRE ATT&CK, PortSwigger Academy, Acun...",Second-Order SQL Injection. In a Second-Order ...,Second-Order SQL Injection. In a Second-Order ...

 Dữ liệu sạch, không có giá trị rỗng.

In [3]:
import pandas as pd
import numpy as np
import os
import re

# Thiết lập đường dẫn tới thư mục dữ liệu (dựa trên cấu trúc project của bạn)
DATA_DIR = '../Dataset/processed'
FILE_NAME = 'cti_dataset_cleaned.csv' # Thay bằng tên file thực tế của bạn
FILE_PATH = os.path.join(DATA_DIR, FILE_NAME)

# Cấu hình hiển thị để dễ dàng quan sát
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)

# Load dữ liệu
try:
    df = pd.read_csv(FILE_PATH).fillna("")
    print(f"Đã load thành công {df.shape[0]} dòng và {df.shape[1]} cột.")
    display(df.head())
except FileNotFoundError:
    print(f"Lỗi: Không tìm thấy file tại {FILE_PATH}. Vui lòng kiểm tra lại đường dẫn.")

Đã load thành công 13161 dòng và 17 cột.

,ID,Title,Category,Attack Type,Scenario Description,Tools Used,Attack Steps,Target Type,Vulnerability,label,Impact,Detection Method,Solution,Tags,Source,text,text_clean
0,1,Authentication Bypass via SQL Injection,Mobile Security,SQL Injection (SQLi),"A login form fails to validate or sanitize input, allowing attackers to log in as admin without knowing the password.","Browser, Burp Suite, SQLMap","1. Reconnaissance: Find a login form on the website (e.g., username and password fields). 2. Test for Injection: Enter a simple payload like ' OR '1'='1 in the username or password field. 3. Analy...","Web Login Portals (e.g., banking, admin dashboards, e-commerce)",Unsanitized input fields in SQL queries,T1078,"Full account takeover, data theft, privilege escalation","Web server logs, anomaly detection (e.g., logins without passwords), WAF alerts","Use prepared statements, Sanitize inputs, Limit login attempts, Use CAPTCHA, Enable MFA","SQLi, Authentication Bypass, Web Security, OWASP Top 10","OWASP, MITRE ATT&CK, DVWA","Authentication Bypass via SQL Injection. A login form fails to validate or sanitize input, allowing attackers to log in as admin without knowing the password. 1. Reconnaissance: Find a login form ...","Authentication Bypass via SQL Injection. A login form fails to validate or sanitize input, allowing attackers to log in as admin without knowing the password. 1. Reconnaissance: Find a login form ..."
1,2,Union-Based SQL Injection,AI Agents & LLM Exploits,SQL Injection,"This attack occurs when a hacker uses the SQL ""UNION"" operator to combine results from a malicious query with a legitimate one, often gaining access to hidden data from the database through a vuln...","SQLMap, Burp Suite, Havij, Browser Developer Tools","1. Identify User Input Points: Attacker finds a search bar, login form, or URL that interacts with the database. 2. Test for Vulnerability: Attacker inputs a single quote ' to break the query. If ...","Web Applications, Login Pages, Search Forms",Improperly filtered input fields that allow SQL queries to be altered,T1190,"Data leakage, Credential theft, Account takeover, Unauthorized database access",Web Application Firewalls (WAF)Log AnalysisInput Sanitization LogsSQL Error Monitoring,Use parameterized queries (Prepared Statements)Sanitize all user inputsDisable detailed SQL error messagesApply least privilege to database accountsRegularly update and patch software,#SQLInjection #WebSecurity #UnionAttack #OWASPTop10 #InjectionFlaws,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger Web Security Academy","Union-Based SQL Injection. This attack occurs when a hacker uses the SQL ""UNION"" operator to combine results from a malicious query with a legitimate one, often gaining access to hidden data from ...","Union-Based SQL Injection. This attack occurs when a hacker uses the SQL ""UNION"" operator to combine results from a malicious query with a legitimate one, often gaining access to hidden data from ..."
2,3,Error-Based SQL Injection,AI Agents & LLM Exploits,SQL Injection,"This attack occurs when an attacker intentionally triggers database errors to extract information. These errors often reveal hidden data or database structure, helping attackers steal credentials ...","SQLMap, Burp Suite, Manual Browser Testing, Havij","1. Identify Input Points:Attacker finds a field like login, search, or URL parameter that interacts with a database.2. Send a Malformed Query:Attacker enters incorrect or unexpected input such as ...","Web Applications, Login Forms, URL Parameters, Admin Panels",Error message exposure due to lack of input validation and improper database handling,T1190,"Information disclosure, Database structure exposure, Entry point for further attacks, Sensitive data leakage",Review and monitor error logsEnable generic error pagesMonitor for unusual user inputsUse WAF to detect SQL errors,Turn off detailed error messages in productionUse parameterized queriesInput validation and sanitizationRegular vulnerability scanningLeast privilege database access,#SQLInjection #ErrorLeakage #WebAppSecurity #OWASPTop10 #DatabaseSecurity,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger Web Security Academy","Error-Based SQL Injection. This attack occurs when an attacker intentionally triggers database errors to extract information. These errors often reveal hidden data or database structure, helping a...","Error-Based SQL Injection. This attack occurs when an attacker intentionally triggers database errors to extract information. These errors often reveal hidden data or database structure, helping a..."
3,4,Blind SQL Injection,AI Agents & LLM Exploits,SQL Injection,"In Blind SQL Injection, the attacker doesn’t see error messages or data output directly, but can still extract data by sending specific questions to the database and observing the application’s be...","SQLMap, Burp Suite, sqlninja, Manual Browser Testing, Python Scripts","1. Find a User Input Point:Attacker finds a place where user input is passed to the database, such as a login form, URL parameter, or search box.2. Test for Blind Injection:The attacker tries a ba...","Web Applications, Login Pages, Search Fields, Query Parameters","No error messages, but user input is still passed to the database and not properly sanitized",T1190,Slow and stealthy data theftFull database compromise over timeCredential and sensitive info leakage,Monitor for slow and repetitive requestsAnalyze behavioral anomalies in logsUse IDS/IPS and WAF to detect patterns,Use parameterized queries (prepared statements)Sanitize and validate all inputHide system errors from usersRate limit and monitor repeated requestsRegular vulnerability scanning,#BlindSQLi #TimeBasedSQLi #WebAppSecurity #OWASPTop10 #DatabaseHacking,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger, SQLMap Docs","Blind SQL Injection. In Blind SQL Injection, the attacker doesn’t see error messages or data output directly, but can still extract data by sending specific questions to the database and observing...","Blind SQL Injection. In Blind SQL Injection, the attacker doesn’t see error messages or data output directly, but can still extract data by sending specific questions to the database and observing..."
4,5,Second-Order SQL Injection,AI Agents & LLM Exploits,SQL Injection,"In a Second-Order SQL Injection, the attacker injects malicious code into a system where it's stored safely at first, but becomes dangerous later when the system uses that data in a different cont...","Burp Suite, SQLMap, Postman, Browser Dev Tools, Manual Testing","1. Identify Stored Input Fields:The attacker looks for forms where input is stored in the database, such as user registration, profile update, or contact forms.2. Inject Malicious Input:Instead of...","Web Applications, User Registration Forms, Profile Update Features",Trusting previously stored unvalidated data in SQL queries,T1505,Delayed data theftUnexpected system behaviorSession hijackingAdmin access through logic manipulation,Log monitoring for delayed query failuresTrack use of stored user input in queriesUse behavior analytics to detect unusual patterns,Sanitize and validate inputs both at entry and at executionUse prepared statements for all dynamic queriesEscape stored user data before reusePerform code reviews for indirect query execution,#SecondOrderSQLi #DelayedInjection #StoredInjection #WebSecurity #OWASPTop10,"OWASP, MITRE ATT&CK, PortSwigger Academy, Acunetix","Second-Order SQL Injection. In a Second-Order SQL Injection, the attacker injects malicious code into a system where it's stored safely at first, but becomes dangerous later when the system uses t...","Second-Order SQL Injection. In a Second-Order SQL Injection, the attacker injects malicious code into a system where it's stored safely at first, but becomes dangerous later when the system uses t..."

In [4]:
#  Tiền xử lý chuyên sâu - Khử định danh thực thể (CTI Entity Masking)
import re

print("=== TIỀN XỬ LÝ CHUYÊN SÂU: MASKING CÁC THỰC THỂ CTI (IOCs) ===")

def mask_cti_entities(df_in):
    df_out = df_in.copy()
    
    # Biên soạn trước các biểu thức chính quy (Regex) tối ưu
    url_pattern = re.compile(r'https?://[^\s<>"\']+')
    ip_pattern = re.compile(r'\b(?:\d{1,3}\.){3}\d{1,3}\b')
    cve_pattern = re.compile(r'\bCVE-\d{4}-\d{4,7}\b', re.IGNORECASE)
    hash_pattern = re.compile(r'\b[A-Fa-f0-9]{64}\b|\b[A-Fa-f0-9]{40}\b|\b[A-Fa-f0-9]{32}\b')
    win_path = re.compile(r'\b[A-Za-z]:\\[a-zA-Z0-9_\.\-\\]+')
    # Định dạng đường dẫn Linux (sử dụng group capture để không nuốt mất khoảng trắng phía trước)
    linux_path = re.compile(r'(^|\s)(/(?:usr|bin|etc|var|tmp|opt|home|sbin|dev|sys|proc|lib|lib64|root)/[a-zA-Z0-9_\.\-/]+)')
    registry_pattern = re.compile(r'\b(?:HKLM|HKCU|HKCR|HKU|HKEY_LOCAL_MACHINE|HKEY_CURRENT_USER|HKEY_CLASSES_ROOT)\\[a-zA-Z0-9_\.\-\\]+', re.IGNORECASE)
    html_tags = re.compile(r'<[^>]+>')
    multi_space = re.compile(r'\s+')

    # Biến đếm thống kê
    counts = {'URL': 0, 'IP': 0, 'CVE': 0, 'Hash': 0, 'Path': 0, 'Registry': 0}

    def mask_text(text):
        if not isinstance(text, str):
            return ""
        
        nonlocal counts
        counts['URL'] += len(url_pattern.findall(text))
        counts['IP'] += len(ip_pattern.findall(text))
        counts['CVE'] += len(cve_pattern.findall(text))
        counts['Hash'] += len(hash_pattern.findall(text))
        counts['Path'] += len(win_path.findall(text)) + len(linux_path.findall(text))
        counts['Registry'] += len(registry_pattern.findall(text))
        
        # Tiến hành thay thế (Masking)
        text = url_pattern.sub('[URL]', text)
        text = ip_pattern.sub('[IP_ADDRESS]', text)
        text = cve_pattern.sub('[CVE_ID]', text)
        text = hash_pattern.sub('[HASH]', text)
        text = win_path.sub('[FILE_PATH]', text)
        text = linux_path.sub(r'\1[FILE_PATH]', text)
        text = registry_pattern.sub('[REGISTRY_KEY]', text)
        text = html_tags.sub(' ', text)          # Xóa các thẻ HTML dư thừa (như <br>)
        text = multi_space.sub(' ', text).strip() # Chuẩn hóa khoảng trắng
        
        return text

    # Tạo cột văn bản đã làm sạch chuyên sâu (giữ lại cột text gốc để phục vụ EDA)
    df_out['text_clean'] = df_out['text'].apply(mask_text)
    
    # In báo cáo thống kê
    print("\nBÁO CÁO THỰC THỂ ĐÃ ĐƯỢC CHUẨN HÓA (MASKING):")
    print("-" * 50)
    for entity, count in counts.items():
        print(f"- {entity:<15}: {count:,} lần")
    print("-" * 50)
    
    return df_out

# Thực thi tiền xử lý chuyên sâu
df_filtered = mask_cti_entities(df)

# Ghi đè file sạch lưu trữ (lúc này đã có thêm cột 'text_clean' được tối ưu hóa cho Model)
df_filtered.to_csv('../Dataset/processed/cti_dataset_cleaned.csv', index=False)
print("\nĐã lưu tập dữ liệu tiền xử lý chuyên sâu vào file: cti_dataset_cleaned.csv")

=== TIỀN XỬ LÝ CHUYÊN SÂU: MASKING CÁC THỰC THỂ CTI (IOCs) ===

BÁO CÁO THỰC THỂ ĐÃ ĐƯỢC CHUẨN HÓA (MASKING):
--------------------------------------------------
- URL            : 1,816 lần
- IP             : 1,272 lần
- CVE            : 191 lần
- Hash           : 34 lần
- Path           : 2,210 lần
- Registry       : 159 lần
--------------------------------------------------

Đã lưu tập dữ liệu tiền xử lý chuyên sâu vào file: cti_dataset_cleaned.csv

# Đoạn bên dưới là tokenize và bỏ stopword tham khảo, có thể chỉnh sửa để tối ưu hơn

In [5]:
# Cell 3: Step 3 - Tokenization, Stopwords Removal & Lemmatization
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

print("[*] Downloading NLTK resources...")
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)  # Fix lỗi NLTK mới thiếu tài nguyên phân câu
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

# 1. Khởi tạo stopwords mặc định tiếng Anh
stop_words = set(stopwords.words('english'))

# --- CÁC TỪ STOPWORD QUAN TRỌNG CẦN GIỮ LẠI CHO CYBERSECURITY ---
# Một số từ trong bộ stopwords tiếng Anh mặc định cực kỳ quan trọng đối với ngữ cảnh bảo mật,
# ví dụ như chỉ định sự phủ định (không có mã hóa/auth) hoặc phương thức tấn công (qua HTTP, tiêm vào).
# Chúng ta sẽ LOẠI BỎ chúng khỏi danh sách stop_words để mô hình giữ lại chúng trong văn bản.
stopwords_to_keep = {
    'not', 'no', 'against',  # Phủ định, chống lại (VD: 'not encrypted', 'no authentication', 'against brute force')
    'into', 'through', 'over', # Vector tấn công (VD: 'inject into', 'tunnel through', 'C2 over HTTP')
    'off', 'down',            # Tác động (VD: 'turn off firewall', 'shutdown system')
    'between',                # Tấn công MITM (VD: 'between client and server')
    'own'                     # Quyền sở hữu (VD: 'own process')
}
stop_words.difference_update(stopwords_to_keep)

# 2. Bổ sung Stopwords chuyên ngành Cybersecurity (Xuất hiện quá phổ biến nhưng không giúp phân biệt kỹ thuật ATT&CK)
cyber_stopwords = {
    'attacker', 'attack', 'threat', 'actor', 'campaign', 'malicious', 'compromise',
    'target', 'victim', 'system', 'vulnerability', 'security', 'cisa', 'mitre',
    'att', 'ck', 'technique', 'adversary', 'incident', 'organization', 'group',
    'detect', 'prevent', 'mitigate', 'analysis', 'analyst', 'report', 'document',
    'information', 'intelligence', 'operation', 'cyber', 'cybersecurity', 'activity',
    'method', 'use', 'using', 'used', 'perform', 'performing', 'performed'
}
stop_words.update(cyber_stopwords)

# 3. Danh sách từ blacklist cần loại bỏ hoàn toàn (Từ rác, từ chỉ thứ tự hoặc siêu dữ liệu)
blacklist_words = {
    'step', 'steps', 'example', 'etc', 'eg', 'ie', 'unnamed', 'nan', 'url',
    'version', 'date', 'author', 'source', 'reference', 'link', 'http', 'https',
    'shown', 'show', 'shows', 'described', 'describe', 'following', 'follow'
}
stop_words.update(blacklist_words)

lemmatizer = WordNetLemmatizer()

def nlp_preprocessing(text):
    if not isinstance(text, str):
        return ""
    
    # Bản đồ bảo vệ các special tokens tránh bị NLTK split dấu ngoặc vuông []
    placeholders = {
        '[url]': 'placeholderurl',
        '[email]': 'placeholderemail',
        '[ip_address]': 'placeholderipaddress',
        '[cve_id]': 'placeholdercveid',
        '[hash]': 'placeholderhash',
        '[file_path]': 'placeholderfilepath',
        '[registry_key]': 'placeholderregistrykey',
        '[number]': 'placeholdernumber'
    }
    
    # Thay thế tạm thời
    for token, ph in placeholders.items():
        text = text.replace(token, ph)
        
    # 1. Tokenize
    tokens = word_tokenize(text.lower())
    
    # 2. Xóa stopword, dấu câu, blacklist & Lemmatize
    cleaned_tokens = []
    for token in tokens:
        # Giữ lại các từ là ký tự chữ/số hoặc là placeholder
        if token.isalnum() or token in placeholders.values():
            if token not in stop_words:
                lemma = lemmatizer.lemmatize(token)
                cleaned_tokens.append(lemma)
                
    # Ghép lại thành chuỗi văn bản hoàn chỉnh
    processed_text = " ".join(cleaned_tokens)
    
    # Khôi phục lại các special tokens ban đầu
    for token, ph in placeholders.items():
        processed_text = processed_text.replace(ph, token)
        
    return processed_text

print("[*] Đang thực hiện Tokenize & Lemmatization tích hợp Stopwords chuyên ngành & Blacklist...")
df_filtered['text_nlp'] = df_filtered['text_clean'].apply(nlp_preprocessing)
print("[+] Hoàn thành Step 3!")

# Hiển thị ví dụ trước và sau
print("\nVí dụ dòng đầu tiên sau khi NLP (text_nlp):")
print(df_filtered.iloc[0]['text_nlp'][:300] + "...")

[*] Downloading NLTK resources...
[*] Đang thực hiện Tokenize & Lemmatization tích hợp Stopwords chuyên ngành & Blacklist...
[+] Hoàn thành Step 3!

Ví dụ dòng đầu tiên sau khi NLP (text_nlp):
authentication bypass via sql injection login form fails validate sanitize input allowing attacker log admin without knowing password reconnaissance find login form website username password field test injection enter simple payload like 1 username password field analyze response login succeeds erro...